/**
 * TimesFM client — Google Research's time-series foundation model.
 *
 * Probabilistic context only. Returns median + quantile band so the caller
 * can never accidentally render a point estimate without uncertainty.
 *
 * Wiring (current):
 *   ingestion/forecast.py runs TimesFM nightly on Dr Non's M5 Max.
 *   It writes public/data/forecasts.json. The frontend reads that file
 *   statically — fast, edge-cacheable, no inference at request time.
 *
 * Backend is swappable behind the `Forecaster` interface:
 *   - StaticJsonForecaster — reads the committed forecasts.json. Real
 *                            TimesFM output, generated by the ingestion
 *                            script.
 *   - StubForecaster       — naive last-value baseline with a noise band.
 *                            Used when the JSON is missing or stale, so
 *                            the dashboard never breaks.
 *
 * Why not HF Inference API: the model uses the `timesfm` Python library,
 * not standard `transformers`. HF's Serverless Inference doesn't serve it.
 * See docs/TIMESFM_NOTES.md.
 */

import staticForecasts from "../../../public/data/forecasts.json";

export type Frequency = "D" | "W" | "M";

export interface ForecastInput {
  symbol?: string;        // for StaticJsonForecaster lookup
  series: number[];       // history — used by stub, ignored by static
  horizon?: number;       // default 5 (trading days)
  frequency?: Frequency;  // default "D"
}

export interface ForecastQuantiles {
  p10: number[];
  p25: number[];
  p50: number[];
  p75: number[];
  p90: number[];
}

export interface ForecastResult {
  median: number[];               // == quantiles.p50, exposed for convenience
  quantiles: ForecastQuantiles;
  horizon: number;
  frequency: Frequency;
  source: "static-json" | "stub";
  model: string;                  // "google/timesfm-2.0-500m-pytorch" or "stub-naive"
  generatedAt: string;
}

interface Forecaster {
  readonly name: ForecastResult["source"];
  readonly model: string;
  forecast(input: Required<ForecastInput>): Promise<{
    median: number[];
    quantiles: ForecastQuantiles;
  } | null>;
}

const DEFAULT_HORIZON: number = 5;
const DEFAULT_FREQUENCY: Frequency = "D";
const FRESHNESS_MS = 48 * 60 * 60 * 1000; // 48h — daily ingestion + weekend tolerance

// ─── Static-JSON backend (real TimesFM output) ──────────────────────

interface ForecastsJson {
  asOf: string;
  model: string;
  horizon: number;
  frequency: string;
  series: Record<string, {
    lastClose: number;
    median: number[];
    quantiles: ForecastQuantiles;
  }>;
}

class StaticJsonForecaster implements Forecaster {
  readonly name = "static-json" as const;
  readonly model: string;
  private readonly data: ForecastsJson;

  constructor(data: ForecastsJson) {
    this.data = data;
    this.model = data.model;
  }

  async forecast(input: Required<ForecastInput>) {
    const entry = this.data.series[input.symbol];
    if (!entry) return null;
    const horizon = Math.min(input.horizon, entry.median.length);
    return {
      median: entry.median.slice(0, horizon),
      quantiles: {
        p10: entry.quantiles.p10.slice(0, horizon),
        p25: entry.quantiles.p25.slice(0, horizon),
        p50: entry.quantiles.p50.slice(0, horizon),
        p75: entry.quantiles.p75.slice(0, horizon),
        p90: entry.quantiles.p90.slice(0, horizon),
      },
    };
  }
}

// ─── Stub backend (naive baseline) ──────────────────────────────────
//
// Used when the static JSON is missing or stale. Deliberately weak — its
// only job is to keep the dashboard rendering without claiming forecasting
// value. The `source: "stub"` field is the contract; the UI surfaces it
// honestly as a "BASELINE" badge.

class StubForecaster implements Forecaster {
  readonly name = "stub" as const;
  readonly model = "stub-naive";

  async forecast(input: Required<ForecastInput>) {
    return Promise.resolve(naiveBaseline(input.series, input.horizon));
  }
}

function naiveBaseline(series: number[], horizon: number) {
  if (series.length === 0) {
    const zeros = new Array(horizon).fill(0);
    return {
      median: zeros,
      quantiles: { p10: zeros, p25: zeros, p50: zeros, p75: zeros, p90: zeros },
    };
  }

  const last = series[series.length - 1];

  // Sample std of recent log-returns (lookback up to 60).
  const lookback = Math.min(60, series.length - 1);
  let stdRet = 0.01;
  if (lookback > 1) {
    const rets: number[] = [];
    for (let i = series.length - lookback; i < series.length; i++) {
      const a = series[i - 1];
      const b = series[i];
      if (a > 0 && b > 0) rets.push(Math.log(b / a));
    }
    const mean = rets.reduce((s, x) => s + x, 0) / rets.length;
    const variance = rets.reduce((s, x) => s + (x - mean) * (x - mean), 0) / Math.max(1, rets.length - 1);
    stdRet = Math.sqrt(variance);
  }

  const median: number[] = [];
  const p10: number[] = [], p25: number[] = [], p75: number[] = [], p90: number[] = [];

  for (let h = 1; h <= horizon; h++) {
    median.push(last);
    // Sqrt-time scaling — band widens with horizon, in line with
    // a random-walk null hypothesis.
    const w = stdRet * Math.sqrt(h);
    p10.push(last * Math.exp(-1.2816 * w));
    p25.push(last * Math.exp(-0.6745 * w));
    p75.push(last * Math.exp( 0.6745 * w));
    p90.push(last * Math.exp( 1.2816 * w));
  }

  return {
    median,
    quantiles: { p10, p25, p50: median, p75, p90 },
  };
}

// ─── Backend selection ──────────────────────────────────────────────

function selectForecaster(): Forecaster {
  const data = staticForecasts as ForecastsJson;
  if (!data || !data.asOf || !data.series) return new StubForecaster();

  const asOfMs = Date.parse(data.asOf);
  if (!Number.isFinite(asOfMs)) return new StubForecaster();
  const ageMs = Date.now() - asOfMs;
  if (ageMs > FRESHNESS_MS) return new StubForecaster();

  return new StaticJsonForecaster(data);
}

// ─── Public surface ─────────────────────────────────────────────────

export async function forecast(input: ForecastInput): Promise<ForecastResult> {
  const symbol    = input.symbol ?? "^SET.BK";
  const horizon   = input.horizon ?? DEFAULT_HORIZON;
  const frequency = input.frequency ?? DEFAULT_FREQUENCY;
  const series    = sanitiseSeries(input.series);

  const f = selectForecaster();
  let out = await f.forecast({ symbol, series, horizon, frequency });

  // StaticJsonForecaster returns null if the symbol isn't in the JSON —
  // fall back to stub so the symbol still gets *something* on screen.
  let source: ForecastResult["source"] = f.name;
  let model = f.model;
  if (!out) {
    const stub = new StubForecaster();
    out = await stub.forecast({ symbol, series, horizon, frequency });
    source = "stub";
    model = "stub-naive (no static entry for symbol)";
  }

  return {
    median: out!.median,
    quantiles: out!.quantiles,
    horizon, frequency,
    source,
    model,
    generatedAt: new Date().toISOString(),
  };
}

function sanitiseSeries(series: number[]): number[] {
  return series.filter((v) => typeof v === "number" && Number.isFinite(v) && v > 0);
}

// ─── Helpers callers commonly need ──────────────────────────────────

/**
 * Probability that the path touches above a threshold by horizon end,
 * approximated from the empirical CDF defined by the five quantiles.
 * Linear interpolation between (p10, p25, p50, p75, p90) — adequate for
 * UI framing, not for risk pricing.
 */
export function probabilityAtOrAbove(
  result: ForecastResult,
  threshold: number,
  horizonStep?: number,
): number {
  const i = (horizonStep ?? result.horizon) - 1;
  const q = result.quantiles;
  const pts: Array<[number, number]> = ([
    [q.p10[i], 0.10],
    [q.p25[i], 0.25],
    [q.p50[i], 0.50],
    [q.p75[i], 0.75],
    [q.p90[i], 0.90],
  ] as Array<[number, number]>).sort((a, b) => a[0] - b[0]);

  if (threshold <= pts[0][0]) return 1 - pts[0][1] * (threshold / pts[0][0]);
  if (threshold >= pts[pts.length - 1][0]) {
    return Math.max(0, 1 - pts[pts.length - 1][1]) * 0.5;
  }
  let cdf = pts[0][1];
  for (let k = 1; k < pts.length; k++) {
    const [v0, c0] = pts[k - 1];
    const [v1, c1] = pts[k];
    if (threshold >= v0 && threshold <= v1) {
      const t = (threshold - v0) / (v1 - v0 || 1);
      cdf = c0 + t * (c1 - c0);
      break;
    }
  }
  return Math.max(0, Math.min(1, 1 - cdf));
}

// Re-exported for callers that may want fresh metadata.
export function staticForecastAsOf(): string | null {
  const data = staticForecasts as ForecastsJson;
  return data?.asOf ?? null;
}
